.386
CODE SEGMENT USE16
    ASSUME CS:CODE
START:
    MOV AX,0
    MOV DS,AX
    MOV BX, WORD PTR DS:[4H] ;读取1H对应内存单元
    MOV CX, WORD PTR DS:[6H]
    MOV BX, WORD PTR DS:[4CH] ;读取13H对应内存单元
    MOV CX, WORD PTR DS:[4EH]
    MOV AH,4CH
    INT 21H
CODE ENDS
    END START
