.386
CODE SEGMENT USE16
    ASSUME CS:CODE,SS:STACK

PINSTRUCT DW ?,? ;储存旧指令的偏移地址和段值

EDIT: 
    CMP AH,00H
    JZ LOP1
    CMP AH,10H
    JZ LOP1
    JMP DWORD PTR CS:PINSTRUCT
LOP1:
    PUSHF
    CALL DWORD PTR CS:PINSTRUCT
    CMP AL,41H ;判断是否大于A
    JAE LOP2
    JMP EXIT
LOP2:
    CMP AL,5AH ;判断是否小于Z
    JBE TRANS
    JMP EXIT
TRANS:
    ADD AL,20H ;将大写变为小写
EXIT:
    IRET
    
START:
    XOR AX,AX
    MOV DS,AX
    MOV AX,DS:[58H]
    MOV CS:PINSTRUCT,AX ;保存旧指令的IP
    MOV AX,DS:[5AH]
    MOV CS:PINSTRUCT+2,AX ;保存旧指令的CS
    CLI
    MOV WORD PTR DS:[58H],OFFSET EDIT
    MOV DS:[5AH],CS
    STI
    MOV DX,OFFSET START+15
    SHR DX,4
    ADD DX,10H
    MOV AL,0 ;DOS31号功能调用
    MOV AH,31H
    INT 21H
CODE ENDS
STACK SEGMENT USE16 STACK
    DB 200 DUP(0)
STACK ENDS
    END START
