.386
CODE SEGMENT USE16
    ASSUME CS:CODE,SS:STACK
START:
    XOR AX,AX
    MOV DS,AX
    CLI
    MOV AX,01E0H
    MOV BX,0F100H
    MOV WORD PTR DS:[58H],AX  ;恢复原地址
    MOV WORD PTR DS:[5AH],BX
    STI
    MOV AH,4CH
    INT 21H
CODE ENDS
STACK SEGMENT USE16 STACK
    DB 200 DUP(0)
STACK ENDS
    END START